// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.android.diskusage.proto;

@SuppressWarnings("hiding")
public final class LegacyScan extends
    com.google.protobuf.nano.MessageNano {

  private static volatile LegacyScan[] _emptyArray;
  public static LegacyScan[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new LegacyScan[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional string path = 1;
  public java.lang.String path;

  public LegacyScan() {
    clear();
  }

  public LegacyScan clear() {
    path = "";
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (!this.path.equals("")) {
      output.writeString(1, this.path);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (!this.path.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.path);
    }
    return size;
  }

  @Override
  public LegacyScan mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          this.path = input.readString();
          break;
        }
      }
    }
  }

  public static LegacyScan parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new LegacyScan(), data);
  }

  public static LegacyScan parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new LegacyScan().mergeFrom(input);
  }
}
