// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.android.diskusage.proto;

@SuppressWarnings("hiding")
public final class PortableFileProto extends
    com.google.protobuf.nano.MessageNano {

  private static volatile PortableFileProto[] _emptyArray;
  public static PortableFileProto[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new PortableFileProto[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional string absolute_path = 1;
  public java.lang.String absolutePath;

  // optional string canonical_path = 2;
  public java.lang.String canonicalPath;

  // optional .BooleanValueProto is_external_storage_emulated = 3;
  public com.google.android.diskusage.proto.BooleanValueProto isExternalStorageEmulated;

  // optional .BooleanValueProto is_external_storage_removable = 4;
  public com.google.android.diskusage.proto.BooleanValueProto isExternalStorageRemovable;

  // optional int64 total_space = 5;
  public long totalSpace;

  // optional .PortableFileProto parent = 6;
  public com.google.android.diskusage.proto.PortableFileProto parent;

  public PortableFileProto() {
    clear();
  }

  public PortableFileProto clear() {
    absolutePath = "";
    canonicalPath = "";
    isExternalStorageEmulated = null;
    isExternalStorageRemovable = null;
    totalSpace = 0L;
    parent = null;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (!this.absolutePath.equals("")) {
      output.writeString(1, this.absolutePath);
    }
    if (!this.canonicalPath.equals("")) {
      output.writeString(2, this.canonicalPath);
    }
    if (this.isExternalStorageEmulated != null) {
      output.writeMessage(3, this.isExternalStorageEmulated);
    }
    if (this.isExternalStorageRemovable != null) {
      output.writeMessage(4, this.isExternalStorageRemovable);
    }
    if (this.totalSpace != 0L) {
      output.writeInt64(5, this.totalSpace);
    }
    if (this.parent != null) {
      output.writeMessage(6, this.parent);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (!this.absolutePath.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.absolutePath);
    }
    if (!this.canonicalPath.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.canonicalPath);
    }
    if (this.isExternalStorageEmulated != null) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(3, this.isExternalStorageEmulated);
    }
    if (this.isExternalStorageRemovable != null) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(4, this.isExternalStorageRemovable);
    }
    if (this.totalSpace != 0L) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt64Size(5, this.totalSpace);
    }
    if (this.parent != null) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(6, this.parent);
    }
    return size;
  }

  @Override
  public PortableFileProto mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          this.absolutePath = input.readString();
          break;
        }
        case 18: {
          this.canonicalPath = input.readString();
          break;
        }
        case 26: {
          if (this.isExternalStorageEmulated == null) {
            this.isExternalStorageEmulated = new com.google.android.diskusage.proto.BooleanValueProto();
          }
          input.readMessage(this.isExternalStorageEmulated);
          break;
        }
        case 34: {
          if (this.isExternalStorageRemovable == null) {
            this.isExternalStorageRemovable = new com.google.android.diskusage.proto.BooleanValueProto();
          }
          input.readMessage(this.isExternalStorageRemovable);
          break;
        }
        case 40: {
          this.totalSpace = input.readInt64();
          break;
        }
        case 50: {
          if (this.parent == null) {
            this.parent = new com.google.android.diskusage.proto.PortableFileProto();
          }
          input.readMessage(this.parent);
          break;
        }
      }
    }
  }

  public static PortableFileProto parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new PortableFileProto(), data);
  }

  public static PortableFileProto parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new PortableFileProto().mergeFrom(input);
  }
}
