// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.android.diskusage.proto;

@SuppressWarnings("hiding")
public final class NativeScanProto extends
    com.google.protobuf.nano.MessageNano {

  private static volatile NativeScanProto[] _emptyArray;
  public static NativeScanProto[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new NativeScanProto[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional string path = 1;
  public java.lang.String path;

  // optional bool rootRequired = 2;
  public boolean rootRequired;

  // optional .PortableStreamProto stream = 3;
  public com.google.android.diskusage.proto.PortableStreamProto stream;

  public NativeScanProto() {
    clear();
  }

  public NativeScanProto clear() {
    path = "";
    rootRequired = false;
    stream = null;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (!this.path.equals("")) {
      output.writeString(1, this.path);
    }
    if (this.rootRequired != false) {
      output.writeBool(2, this.rootRequired);
    }
    if (this.stream != null) {
      output.writeMessage(3, this.stream);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (!this.path.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.path);
    }
    if (this.rootRequired != false) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBoolSize(2, this.rootRequired);
    }
    if (this.stream != null) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(3, this.stream);
    }
    return size;
  }

  @Override
  public NativeScanProto mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          this.path = input.readString();
          break;
        }
        case 16: {
          this.rootRequired = input.readBool();
          break;
        }
        case 26: {
          if (this.stream == null) {
            this.stream = new com.google.android.diskusage.proto.PortableStreamProto();
          }
          input.readMessage(this.stream);
          break;
        }
      }
    }
  }

  public static NativeScanProto parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new NativeScanProto(), data);
  }

  public static NativeScanProto parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new NativeScanProto().mergeFrom(input);
  }
}
